apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.service.enableDualStack }}
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv6
    - IPv4
  {{- end }}
  type: {{ .Values.service.agentMemory.type }}
  ports:
    - name: public-port
      port: {{ .Values.service.agentMemory.port }}
      targetPort: {{ .Values.service.agentMemory.port }}
      {{- if eq .Values.service.agentMemory.type "NodePort" }}
      nodePort: {{ .Values.service.agentMemory.nodePort }}
      {{- end}}
      protocol: TCP
  selector:
    app: {{ .Values.image.name }}