apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redis.name" . }}-configmap
  namespace: {{ .Values.namespace }}
data:
  redis.conf: |
{{- include "config-redis.conf" . }}

  sentinel.conf: |
{{- include "config-sentinel.conf" . }}

  users.acl: |
{{- include "config-users.acl" . }}

  sentinel-users.acl: |
{{- include "config-sentinel-users.acl" . }}

