db:
  host: "mariadb-mariadb-master.resource.svc.cluster.local."
  port: 3330
  user_name: "anyshare"
  password: "***"
  db_name: "dip_data_operator_hub"
  charset: "utf8mb4"

opensearch:
  host: "opensearch-master.resource.svc.cluster.local."
  port: 9200
  protocol: http
  user: "admin"
  password: "***"
  version: 7.10.0