{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: apps/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: "kubernetes.io/hostname"
      {{- if ne .Values.runMode "dev" }}
      {{- if eq .Values.enableSecurityContext true }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          {{- if ne .Values.runMode "dev" }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.service.repository }}:{{ .Values.image.service.tag }}"
          imagePullPolicy: {{ .Values.image.service.pullPolicy }}
          {{- else}}
          image: "acr.aishu.cn/client/godevenv:1.16.2"
          {{- end}}

          env:
              - name: DB_TYPE
                value: {{ .Values.depServices.rds.type | quote }}
            {{- if .Values.service.loggerOutput}}
              - name: LOGOUT
                value: {{ .Values.service.loggerOutput }}
            {{- end}}
            {{- if .Values.serviceName}}
              - name: SERVICE_NAME
                value: {{ .Values.serviceName }}
            {{- end}}
            {{- if .Values.env.language}}
              - name: LANG
                value: {{ .Values.env.language }}
              - name: LC_ALL
                value: {{ .Values.env.language }}
            {{- end}}
            {{- if .Values.env.timezone}}
              - name: TZ
                value: {{ .Values.env.timezone }}
            {{- end}}
              - name: RDSHOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Release.Name }}-yaml
                    key: RDSHOST
              - name: RDSPORT
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Release.Name }}-yaml
                    key: RDSPORT
              - name: RDSUSER
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Release.Name }}-yaml
                    key: RDSUSER
              - name: RDSPASS
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Release.Name }}-yaml
                    key: RDSPASS
              - name: RDSDBNAME
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Release.Name }}-yaml
                    key: RDSDBNAME

              - name: DM_SVC_PATH
                value: /tmp/rds_conf/
          ports:
            - name: public-port
              containerPort: {{ .Values.service.port }}
          {{- if ne .Values.runMode "dev"}}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: public-port
            initialDelaySeconds: {{ .Values.service.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.service.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.service.readinessProbe.failureThreshold }}
          {{- end}}
          volumeMounts:
            - name: {{ .Release.Name }}-yaml
              mountPath: /sysvol/conf/
            - name: {{ .Release.Name }}-secret-yaml
              mountPath: /sysvol/conf/secret
            {{- if eq .Values.runMode "dev" }}
            - name: home-path
              mountPath: /root
            {{- end }}
          {{- if ne .Values.runMode "dev" }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          {{ end }}
      volumes:
        - name: {{ .Release.Name }}-yaml
          configMap:
            name: {{ .Release.Name }}-yaml
        - name: {{ .Release.Name }}-secret-yaml
          secret:
            secretName: {{ .Release.Name }}-secret-yaml
        {{ if eq .Values.runMode "dev" }}
        - name: home-path
          hostPath:
            path: /root
        {{ end }}
      dnsConfig:
         options:
           - name: single-request-reopen
           - name: use-vc
