{{- if .Values.service.agentApp.ingress.enabled -}}
{{ if .Values.service.agentApp.ingress.interface }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.moduleName }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500M"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/service-upstream: "true" # 使用客户端源ip
spec:
{{- if .Values.service.ingressclassname }}
  ingressClassName: "{{.Values.service.ingressclassname}}"
{{- end }}
  rules:
  - http:
      paths:
        {{- range .Values.service.agentApp.ingress.interface.path }}
        - path: {{ . }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $.Values.moduleName }}
              port:
                number: {{ $.Values.service.agentApp.port }}
        {{- end }}
{{ end }}
{{- end }}
