app:
  name: agent-memory
  version: 1.0.0
  debug: false

server:
  host: 0.0.0.0
  port: 30790
  workers: 1

memory:
  max_tokens: 2000

db:
  host: XXX
  port: 30006
  user: root
  password: "***"
  database: dip_data_agent

llm:
  provider: "openai"
  base_url: "http://mf-model-api:9898/api/private/mf-model-api/v1"
  model: "Tome-Max"
  api_key: "default"

embedder:
  provider: "openai"
  model: "embedding"
  base_url: "http://mf-model-api:9898/api/private/mf-model-api/v1/small-model"
  api_key: "default"
  embedding_dims: 768

vector_store:
  provider: "opensearch"
  collection_name: "dip_dataagent_memory"
  host: "opensearch-master"
  port: 30920
  user: "admin"
  password: "***"
  embedding_model_dims: 768 

rerank:
  # rerank_url: "http://XXX:18343/v1/rerank"
  rerank_url: "http://mf-model-api:9898/api/private/mf-model-api/v1/small-model/reranker"
  rerank_model: "reranker"