{{- if .Values.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc }}
  password: {{ if .Values.secret.password }}{{ .Values.secret.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  mongodb.keyfile: {{ if .Values.secret.keyfile }}{{ .Values.secret.keyfile | b64enc }}{{ else }}{{ randAlphaNum 1024 | b64enc }}{{ end }}
{{- end }}
