db:
  host: "mariadb-mariadb-master.resource.svc.cluster.local."
  port: 3330
  user_name: "root"
  password: "***"
  db_name: "dip_data_operator_hub"
  charset: "utf8mb4"
redis:
  connectInfo:
    username: "root"
    password: "***"
    host: ""
    port: 26379
    masterHost: ""
    masterPort: 26379
    slaveHost: ""
    slavePort: 26379
    sentinelHost: "proton-redis-proton-redis-sentinel.resource.svc.cluster.local"
    sentinelPort: 26379
    sentinelUsername: "root"
    sentinelPassword: "***"
    masterGroupName: "mymaster"
