services:
  agent-app_dev:
    container_name: agent-app_dev
    image: acr.aishu.cn/public/golang:1.23.7-ubuntu22.04.20241202-2-20250319.1
    stdin_open: true
    tty: true
    pull_policy: always
    privileged: true
    entrypoint: bash ./entrypoint.sh
    ports:
      - "30777:30777"
    dns:
      - 10.96.0.10
      - XXX
    volumes:
      - type: bind
        source: /root/.vscode-server
        target: /root/.vscode-server
      - type: bind
        source: /root/.gitconfig
        target: /root/.hostgitconfig
      - type: bind
        source: .
        target: /root/agent-app
    working_dir: /root/agent-app
